window.PRELOADED_ADS_REPORT_ROWS = [
  {
    "id": "adset-traffic-1",
    "campaign": "流量-LINE導流",
    "adSet": "導LINE_35-65_房產投資",
    "ad": "",
    "spend": 3801.0,
    "reach": 30273.0,
    "impressions": 37751.0,
    "frequency": 1.247019,
    "clicks": 1014.0,
    "allClicks": 1308.0,
    "ctr": 2.686022,
    "cpc": 3.748521,
    "result": 888.0,
    "resultMetric": "actions:omni_landing_page_view",
    "resultLabel": "落地頁瀏覽",
    "costPerResult": 4.28040541,
    "follows": 0,
    "fbLikes": 0,
    "igFollows": 0,
    "videoPlays": 7071.0,
    "video100": 104.0,
    "quality": "",
    "engagementRank": "",
    "conversionRank": "",
    "source": "導LINE_廣告組合.csv",
    "levelType": "adset",
    "level": "廣告組合",
    "groupId": "traffic",
    "groupName": "流量-LINE導流"
  },
  {
    "id": "creative-traffic-1",
    "campaign": "流量-LINE導流",
    "adSet": "",
    "ad": "這幾年我在杜拜看房地產市場",
    "spend": 869.0,
    "reach": 7991.0,
    "impressions": 8930.0,
    "frequency": 1.117507,
    "clicks": 360.0,
    "allClicks": 440.0,
    "ctr": 4.031355,
    "cpc": 2.413889,
    "result": 309.0,
    "resultMetric": "actions:omni_landing_page_view",
    "resultLabel": "落地頁瀏覽",
    "costPerResult": 2.81229773,
    "follows": 0.0,
    "fbLikes": 0,
    "igFollows": 0.0,
    "videoPlays": 0,
    "video100": 0,
    "quality": "低於平均 - 倒數 35% 的廣告",
    "engagementRank": "高於平均",
    "conversionRank": "低於平均 - 倒數 20% 的廣告",
    "source": "導LINE_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "traffic",
    "groupName": "流量-LINE導流"
  },
  {
    "id": "creative-traffic-2",
    "campaign": "流量-LINE導流",
    "adSet": "",
    "ad": "海外投資讓大家擔心的一點",
    "spend": 213.0,
    "reach": 1684.0,
    "impressions": 1747.0,
    "frequency": 1.037411,
    "clicks": 45.0,
    "allClicks": 76.0,
    "ctr": 2.575844,
    "cpc": 4.733333,
    "result": 38.0,
    "resultMetric": "actions:omni_landing_page_view",
    "resultLabel": "落地頁瀏覽",
    "costPerResult": 5.60526316,
    "follows": 0.0,
    "fbLikes": 0,
    "igFollows": 0.0,
    "videoPlays": 1609.0,
    "video100": 6.0,
    "quality": "低於平均 - 倒數 35% 的廣告",
    "engagementRank": "平均",
    "conversionRank": "低於平均 - 倒數 35% 的廣告",
    "source": "導LINE_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "traffic",
    "groupName": "流量-LINE導流"
  },
  {
    "id": "creative-traffic-3",
    "campaign": "流量-LINE導流",
    "adSet": "",
    "ad": "海外買房大家最擔心的就是售後服務",
    "spend": 508.0,
    "reach": 4118.0,
    "impressions": 4970.0,
    "frequency": 1.206897,
    "clicks": 145.0,
    "allClicks": 238.0,
    "ctr": 2.917505,
    "cpc": 3.503448,
    "result": 113.0,
    "resultMetric": "actions:omni_landing_page_view",
    "resultLabel": "落地頁瀏覽",
    "costPerResult": 4.49557522,
    "follows": 0.0,
    "fbLikes": 0,
    "igFollows": 0.0,
    "videoPlays": 4576.0,
    "video100": 44.0,
    "quality": "低於平均 - 倒數 35% 的廣告",
    "engagementRank": "高於平均",
    "conversionRank": "低於平均 - 倒數 35% 的廣告",
    "source": "導LINE_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "traffic",
    "groupName": "流量-LINE導流"
  },
  {
    "id": "creative-traffic-4",
    "campaign": "流量-LINE導流",
    "adSet": "",
    "ad": "海外資產該怎麼選",
    "spend": 110.0,
    "reach": 1862.0,
    "impressions": 1866.0,
    "frequency": 1.002148,
    "clicks": 45.0,
    "allClicks": 45.0,
    "ctr": 2.411576,
    "cpc": 2.444444,
    "result": 42.0,
    "resultMetric": "actions:omni_landing_page_view",
    "resultLabel": "落地頁瀏覽",
    "costPerResult": 2.61904762,
    "follows": 0.0,
    "fbLikes": 0,
    "igFollows": 0.0,
    "videoPlays": 0,
    "video100": 0,
    "quality": "-",
    "engagementRank": "-",
    "conversionRank": "-",
    "source": "導LINE_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "traffic",
    "groupName": "流量-LINE導流"
  },
  {
    "id": "creative-traffic-5",
    "campaign": "流量-LINE導流",
    "adSet": "",
    "ad": "杜拜房市現在看的",
    "spend": 1597.0,
    "reach": 8086.0,
    "impressions": 12515.0,
    "frequency": 1.547737,
    "clicks": 320.0,
    "allClicks": 374.0,
    "ctr": 2.556932,
    "cpc": 4.990625,
    "result": 294.0,
    "resultMetric": "actions:omni_landing_page_view",
    "resultLabel": "落地頁瀏覽",
    "costPerResult": 5.43197279,
    "follows": 0.0,
    "fbLikes": 0,
    "igFollows": 0.0,
    "videoPlays": 472.0,
    "video100": 23.0,
    "quality": "低於平均 - 倒數 35% 的廣告",
    "engagementRank": "平均",
    "conversionRank": "低於平均 - 倒數 35% 的廣告",
    "source": "導LINE_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "traffic",
    "groupName": "流量-LINE導流"
  },
  {
    "id": "creative-traffic-6",
    "campaign": "流量-LINE導流",
    "adSet": "",
    "ad": "即將開盤的物件",
    "spend": 504.0,
    "reach": 6669.0,
    "impressions": 7723.0,
    "frequency": 1.158045,
    "clicks": 99.0,
    "allClicks": 135.0,
    "ctr": 1.281885,
    "cpc": 5.090909,
    "result": 92.0,
    "resultMetric": "actions:omni_landing_page_view",
    "resultLabel": "落地頁瀏覽",
    "costPerResult": 5.47826087,
    "follows": 0.0,
    "fbLikes": 0,
    "igFollows": 0.0,
    "videoPlays": 414.0,
    "video100": 31.0,
    "quality": "平均",
    "engagementRank": "平均",
    "conversionRank": "低於平均 - 倒數 35% 的廣告",
    "source": "導LINE_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "traffic",
    "groupName": "流量-LINE導流"
  },
  {
    "id": "adset-engage-1",
    "campaign": "互動-粉專按讚",
    "adSet": "導粉專_35-65_房產投資",
    "ad": "",
    "spend": 14863.0,
    "reach": 58633.0,
    "impressions": 108358.0,
    "frequency": 1.848072,
    "clicks": 3794.0,
    "allClicks": 5167.0,
    "ctr": 3.501357,
    "cpc": 3.917501,
    "result": 4228.0,
    "resultMetric": "total_profile_visits",
    "resultLabel": "個人檔案瀏覽",
    "costPerResult": 3.5153737,
    "follows": 271.0,
    "fbLikes": 206.0,
    "igFollows": 65.0,
    "videoPlays": 81909.0,
    "video100": 2747.0,
    "quality": "",
    "engagementRank": "",
    "conversionRank": "",
    "source": "導粉專_廣告組合.csv",
    "levelType": "adset",
    "level": "廣告組合",
    "groupId": "engage",
    "groupName": "互動-粉專按讚"
  },
  {
    "id": "creative-engage-1",
    "campaign": "互動-粉專按讚",
    "adSet": "",
    "ad": "這幾年我在杜拜看房地產市場",
    "spend": 1398.0,
    "reach": 12038.0,
    "impressions": 15472.0,
    "frequency": 1.285263,
    "clicks": 633.0,
    "allClicks": 956.0,
    "ctr": 4.091262,
    "cpc": 2.208531,
    "result": 615.0,
    "resultMetric": "total_profile_visits",
    "resultLabel": "個人檔案瀏覽",
    "costPerResult": 2.27317073,
    "follows": 12.0,
    "fbLikes": 12.0,
    "igFollows": 0.0,
    "videoPlays": 10.0,
    "video100": 2.0,
    "quality": "低於平均 - 倒數 35% 的廣告",
    "engagementRank": "-",
    "conversionRank": "-",
    "source": "導粉專_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "engage",
    "groupName": "互動-粉專按讚"
  },
  {
    "id": "creative-engage-2",
    "campaign": "互動-粉專按讚",
    "adSet": "",
    "ad": "買房保值的重點",
    "spend": 185.0,
    "reach": 551.0,
    "impressions": 763.0,
    "frequency": 1.384755,
    "clicks": 61.0,
    "allClicks": 77.0,
    "ctr": 7.994758,
    "cpc": 3.032787,
    "result": 21.0,
    "resultMetric": "total_profile_visits",
    "resultLabel": "個人檔案瀏覽",
    "costPerResult": 8.80952381,
    "follows": 6.0,
    "fbLikes": 5.0,
    "igFollows": 1.0,
    "videoPlays": 711.0,
    "video100": 15.0,
    "quality": "低於平均 - 倒數 35% 的廣告",
    "engagementRank": "-",
    "conversionRank": "-",
    "source": "導粉專_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "engage",
    "groupName": "互動-粉專按讚"
  },
  {
    "id": "creative-engage-3",
    "campaign": "互動-粉專按讚",
    "adSet": "",
    "ad": "杜拜不就是一個獨立的國家嗎？",
    "spend": 2884.0,
    "reach": 16272.0,
    "impressions": 20361.0,
    "frequency": 1.251291,
    "clicks": 721.0,
    "allClicks": 1162.0,
    "ctr": 3.541083,
    "cpc": 4.0,
    "result": 846.0,
    "resultMetric": "total_profile_visits",
    "resultLabel": "個人檔案瀏覽",
    "costPerResult": 3.40898345,
    "follows": 93.0,
    "fbLikes": 75.0,
    "igFollows": 18.0,
    "videoPlays": 19828.0,
    "video100": 1289.0,
    "quality": "低於平均 - 倒數 35% 的廣告",
    "engagementRank": "-",
    "conversionRank": "-",
    "source": "導粉專_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "engage",
    "groupName": "互動-粉專按讚"
  },
  {
    "id": "creative-engage-4",
    "campaign": "互動-粉專按讚",
    "adSet": "",
    "ad": "杜拜房市現在看的",
    "spend": 49.0,
    "reach": 249.0,
    "impressions": 278.0,
    "frequency": 1.116466,
    "clicks": 16.0,
    "allClicks": 18.0,
    "ctr": 5.755396,
    "cpc": 3.0625,
    "result": 16.0,
    "resultMetric": "total_profile_visits",
    "resultLabel": "個人檔案瀏覽",
    "costPerResult": 3.0625,
    "follows": 3.0,
    "fbLikes": 3.0,
    "igFollows": 0.0,
    "videoPlays": 0,
    "video100": 0,
    "quality": "-",
    "engagementRank": "-",
    "conversionRank": "-",
    "source": "導粉專_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "engage",
    "groupName": "互動-粉專按讚"
  },
  {
    "id": "creative-engage-5",
    "campaign": "互動-粉專按讚",
    "adSet": "",
    "ad": "杜拜精品兩房",
    "spend": 695.0,
    "reach": 3299.0,
    "impressions": 3878.0,
    "frequency": 1.175508,
    "clicks": 168.0,
    "allClicks": 230.0,
    "ctr": 4.33213,
    "cpc": 4.136905,
    "result": 204.0,
    "resultMetric": "total_profile_visits",
    "resultLabel": "個人檔案瀏覽",
    "costPerResult": 3.40686275,
    "follows": 14.0,
    "fbLikes": 13.0,
    "igFollows": 1.0,
    "videoPlays": 3751.0,
    "video100": 86.0,
    "quality": "低於平均 - 倒數 35% 的廣告",
    "engagementRank": "-",
    "conversionRank": "-",
    "source": "導粉專_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "engage",
    "groupName": "互動-粉專按讚"
  },
  {
    "id": "creative-engage-6",
    "campaign": "互動-粉專按讚",
    "adSet": "",
    "ad": "杜拜現在不缺豪宅",
    "spend": 2437.0,
    "reach": 7469.0,
    "impressions": 10821.0,
    "frequency": 1.448788,
    "clicks": 484.0,
    "allClicks": 582.0,
    "ctr": 4.472784,
    "cpc": 5.035124,
    "result": 512.0,
    "resultMetric": "total_profile_visits",
    "resultLabel": "個人檔案瀏覽",
    "costPerResult": 4.75976562,
    "follows": 51.0,
    "fbLikes": 30.0,
    "igFollows": 21.0,
    "videoPlays": 10469.0,
    "video100": 319.0,
    "quality": "低於平均 - 倒數 35% 的廣告",
    "engagementRank": "-",
    "conversionRank": "-",
    "source": "導粉專_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "engage",
    "groupName": "互動-粉專按讚"
  },
  {
    "id": "creative-engage-7",
    "campaign": "互動-粉專按讚",
    "adSet": "",
    "ad": "即將開盤的物件",
    "spend": 1257.0,
    "reach": 5396.0,
    "impressions": 8694.0,
    "frequency": 1.611193,
    "clicks": 164.0,
    "allClicks": 212.0,
    "ctr": 1.886358,
    "cpc": 7.664634,
    "result": 179.0,
    "resultMetric": "total_profile_visits",
    "resultLabel": "個人檔案瀏覽",
    "costPerResult": 7.02234637,
    "follows": 14.0,
    "fbLikes": 13.0,
    "igFollows": 1.0,
    "videoPlays": 24.0,
    "video100": 4.0,
    "quality": "平均",
    "engagementRank": "-",
    "conversionRank": "-",
    "source": "導粉專_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "engage",
    "groupName": "互動-粉專按讚"
  },
  {
    "id": "creative-engage-8",
    "campaign": "互動-粉專按讚",
    "adSet": "",
    "ad": "DANUBE - Greenz",
    "spend": 4630.0,
    "reach": 21592.0,
    "impressions": 35892.0,
    "frequency": 1.662282,
    "clicks": 1197.0,
    "allClicks": 1474.0,
    "ctr": 3.335005,
    "cpc": 3.868003,
    "result": 1412.0,
    "resultMetric": "total_profile_visits",
    "resultLabel": "個人檔案瀏覽",
    "costPerResult": 3.27903683,
    "follows": 59.0,
    "fbLikes": 41.0,
    "igFollows": 18.0,
    "videoPlays": 35127.0,
    "video100": 826.0,
    "quality": "低於平均 - 倒數 35% 的廣告",
    "engagementRank": "-",
    "conversionRank": "-",
    "source": "導粉專_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "engage",
    "groupName": "互動-粉專按讚"
  },
  {
    "id": "creative-engage-9",
    "campaign": "互動-粉專按讚",
    "adSet": "",
    "ad": "模範開發商 HRE",
    "spend": 1328.0,
    "reach": 8638.0,
    "impressions": 12199.0,
    "frequency": 1.412248,
    "clicks": 350.0,
    "allClicks": 456.0,
    "ctr": 2.869088,
    "cpc": 3.794286,
    "result": 423.0,
    "resultMetric": "total_profile_visits",
    "resultLabel": "個人檔案瀏覽",
    "costPerResult": 3.13947991,
    "follows": 19.0,
    "fbLikes": 14.0,
    "igFollows": 5.0,
    "videoPlays": 11989.0,
    "video100": 206.0,
    "quality": "低於平均 - 倒數 35% 的廣告",
    "engagementRank": "-",
    "conversionRank": "-",
    "source": "導粉專_素材.csv",
    "levelType": "creative",
    "level": "素材",
    "groupId": "engage",
    "groupName": "互動-粉專按讚"
  }
];
